travis:
  secure:
    BINSTAR_TOKEN: pyBaEHyD3Nw22LYzaXnxXa1v2nRvaHhIUTJ8qGVfXREzteF0ZAxfiFa7CfJ3A/99ALDBbHQV804Bo+CRkrw6VbeGn09FLAFkGKUKXWKmq6X0KfS0CmDo7orUAZGkkfUlO7m3wMR0uSgUAmJ3Ji9e4mH2QSzileun+1qf/wgqBhl4NCHcqC5O20jRappaBUgg8H8BuzsqehPmNY87VFMEA4gsuhVuaTfosI3nTKk+Xybu+RsY/OZaHrsmL3u3Lo18+Z/2srcSSO7UILR7tTKbmstbUAJ/ffce8QXnqrM9zR0zLjNysz10epL9rUPdkk7NYIttNBrYBGOe9ZSFKLrUGUtftqEYTz3CyBuYAa1vlIiovV3WA6UJ3slWUfSdutQwXp2fXLNVv+DZscVxhAJZVRPiidkHBQCBus9hb36tZGp8N51YNOzkZviZxbylUg9Iye+8guELlqtfCDazhtdwQaxV22gpGyDkrC0HFmjpF/J1Ki3uo3qZ0uR7Cn9bpFeyB8wlMvGJz/zHu8BjbG+S3K/9JLZhOwdbv+2URx4G45pVkOfK/IwqfSdL+ctKORn0IEn1p9Sn1Z8znLQb84FSIGHVHybBV3/6d0VF/y/NEga60vZWfitJq7qREUXBzG/NuvbGGm180N5HqcpIDoDZExDvKsoC80RyFhmBT/BmsMw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
